---

- name: Add proxmox apt source
  block:
    - name: add apt key
      ansible.builtin.get_url:
        url: https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg
        dest: /etc/apt/keyrings/docker.gpg

    - name: add apt source
      ansible.builtin.apt_repository:
      repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg] http://download.proxmox.com/debian/pve bullseye pve-no-subscription"
      state: present

- name: Edit hosts file for postfix
  shell: |
    echo "127.0.0.1       localhost
    {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}         mail.exemple.com {{ result.stdout }}
    # The following lines are desirable for IPv6 capable hosts
    ::1             localhost ip6-localhost ip6-loopback
    ff02::1         ip6-allnodes
    ff02::2         ip6-allrouters" > /etc/hosts

- name: Edit interface file for disable ipv6
  shell: sed -i "s/iface {{ ansible_default_ipv4.interface }} inet6 auto/# iface {{ ansible_default_ipv4.interface }} inet6 auto/g" /etc/network/interfaces

- name: Install postfix
  ansible.builtin.apt:
    name: postfix
    state: present

- name: Install open-iscsi
  ansible.builtin.apt:
    name: open-iscsi
    state: present

- name: Install proxmox-ve
  ansible.builtin.apt:
    name: proxmox-ve
    state: present