---

- name: remove non free repo proxmox
  shell: sed -i "s/deb/#deb/g" /etc/apt/sources.list.d/pve-enterprise.list 2>/dev/null

- name: Remove old linux kernel
  ansible.builtin.apt:
    name: linux-image-5.10*
    state: absent

- name: download debian lxc template
  shell: pveam download local $(pveam available --section system | grep debian-11 | cut -d" " -f11)