################
version: '3.9' #
services:      #
################
#
#
##########################################################
  CN_Portainer:
    # -------------------------------------------------- #
    image: 'portainer/portainer-ce'
    container_name: 'CN_Portainer'
    # -------------------------------------------------- #
    network_mode: 'bridge'
    hostname: 'CN_Portainer'
    # -------------------------------------------------- #
    restart: 'always'
    # -------------------------------------------------- #
    ports:
      - '8000:8000'
      - '9443:9443'
    volumes:
      - 'Portainer_Data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    labels:
      hidden: 'true'
##########################################################
#
#
#############################
#  Déclaration des volumes  #
#############################
volumes:
  # ----------------------- #
  Portainer_Data:
    external: false
  # ----------------------- #